### PR TITLE
Workspace Factory #16: Configure Options Object

### PR DESCRIPTION
**Pull request by edauterman**
Allows the user to configure the options object used to inject Blockly with checkboxes and text fields. Updates the preview workspace automatically to reflect changes to the options object. Uses the Blockly default values to start with and allows the user to revert to those with a button. On changing from a single flyout to categories or categories to a single flyout, asks the user if they would like to use category or flyout specific default option values (e.g. scrollbars, trashcan, etc.). Allows the user to save the options object to a file. 

Files changed: index.html, style.css (very minor, small button), wfactory_controller.js, wfactory_model.js
options no grid
options with grid

---

This change is [Reviewable](https://reviewable.io/reviews/evd2014/blockly/41)

### CODE REVIEW

**Comment by edauterman** [comment]
+@picklesrus +@vicng +@quachtina96 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41#-:-KOqGnwPeB0Aph1UrfE1:b-wq1gnr)_

**Comment by vicng** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/index.html, line 116 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOqXfpLn7Qowhn6VK6f:-KOqXfpLn7Qowhn6VK6g:brsrg5r) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/index.html#L116)):_

> ``` HTML
>     <button class="small" id="button_standardOptions">Standard Options</button>
>     <form id="workspace_options">
>       <input type="checkbox" id="collapse_checkbox" name="collapse">Collapsible Blocks<br>
> ```

Not sure what the naming convention is for IDs, but I like to group similar html elements together with the same prefix:

eg.
"input_option_comment_checkbox"
"input_option_css_checkbox"

or 

"option_comment_checkbox"
"option_css_checkbox"

Katelyn?

---

_[demos/blocklyfactory/workspacefactory/index.html, line 760 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvux1xoS_UQkJEp7pE:-KOvux1xoS_UQkJEp7pF:b4153lt) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/index.html#L760)):_

> ``` HTML
>   // Unchecking the grid checkbox removes the grid object from the options object and
>   // hides the grid options.
>   document.getElementById('grid_checkbox').addEventListener('change', function(e) {
> ```

As discussed offline, this could be simplified by just regenerating all the options after making a change to any option.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 60 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOqhpBFJLEWhSObW3WU:-KOqhpBFJLEWhSObW3WV:b-jnr44b) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L60)):_

> ``` JavaScript
>         return;
>       }
>       // Create the new category.
> ```

Add line breaks!

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 64 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvqNie43Rf0hhVEzJX:-KOvqNie43Rf0hhVEzJY:bhqsx77) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L64)):_

> ``` JavaScript
>       // Allow the user to use the default options for injecting the workspace
>       // when there are categories.
>       this.allowToSetDefaultOptions();
> ```

Can this only be called once in this method? Seems strange that it's called twice.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 659 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvqtqMGKdTVgspoMqB:-KOvqtqMGKdTVgspoMqC:bxpk223) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L659)):_

> ``` JavaScript
>     this.view.addEmptyCategoryMessage();
> 
>     // Allow the user to set the default configuration options for a single
> ```

Call allowToSetDefaultOptions() once at the end of if/else

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 731 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvq4QPFqol2A6F2mBz:-KOvq4QPFqol2A6F2mC-:b-bc5xtx) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L731)):_

> ``` JavaScript
>   this.toolboxWorkspace.clear();
>   this.toolboxWorkspace.clearUndo();
>   if (hasCategories) {
> ```

I don't think this should this be called here.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 354 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvvDEbmku33uyDc-yE:-KOvvDEbmku33uyDc-yF:b-vjgpvt) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_model.js#L354)):_

> ``` JavaScript
>   return this.preloadXml;
> };
> ```

As discussed, these new methods could be removed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41)_

**Comment by edauterman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/index.html, line 116 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOqXfpLn7Qowhn6VK6f:-KOwDPieCP_6GjvCO0FW:b-enimlf) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/index.html#L116)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Not sure what the naming convention is for IDs, but I like to group similar html elements together with the same prefix:
> 
> eg.
> "input_option_comment_checkbox"
> "input_option_css_checkbox"
> 
> or 
> 
> "option_comment_checkbox"
> "option_css_checkbox"
> 
> Katelyn?
> </details>
> Added option prefix to all regular options, and gridOption and zoomOption prefix to grid and zoom sub-options. 

---

_[demos/blocklyfactory/workspacefactory/index.html, line 760 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvux1xoS_UQkJEp7pE:-KOw72WVnSE-OtoOhG-C:b-3nd6da) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/index.html#L760)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> As discussed offline, this could be simplified by just regenerating all the options after making a change to any option.
> </details>
> Refactored to generate a new options object every time the options are updated. 

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 60 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOqhpBFJLEWhSObW3WU:-KOw702KdQsbLpo5eY89:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L60)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Add line breaks!
> </details>
> Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 64 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvqNie43Rf0hhVEzJX:-KOw7AGr4dtCg22tZ5gd:b-wp7jvc) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L64)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Can this only be called once in this method? Seems strange that it's called twice.
> </details>
> The behavior is correct (only 1 of those will ever get called), but refactored to make it so that there's only one call to allowToSetDefaultOptions() to make it more readable.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 659 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvqtqMGKdTVgspoMqB:-KOw93IEiqYjDJrCbivg:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L659)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Call allowToSetDefaultOptions() once at the end of if/else
> </details>
> Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 731 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvq4QPFqol2A6F2mBz:-KOw9Z_bxFM7GRdCsB04:b-dpg0x2) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L731)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> I don't think this should this be called here.
> </details>
> Talked about this offline, ok to leave it there as it's tied to a button.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 354 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOvvDEbmku33uyDc-yE:-KOw9LLpKFL1MYDAgrgV:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/162e69a30ae91b871c97503e397eb7bd66812681/demos/blocklyfactory/workspacefactory/wfactory_model.js#L354)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> As discussed, these new methods could be removed.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/index.html, line 772 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwHfmfGxKdzAiOjJ_F:-KOwHfmfGxKdzAiOjJ_G:big77fy) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/index.html#L772)):_

> ``` HTML
> 
>   // Add event listeners for all options checkboxes and text fields (not zoom and grid).
>   var options = document.getElementById('workspace_options').children;
> ```

I'd prefer this to simpler by adding the change function to each element directly. It's easier just to be explicit instead of relying on naming conditions.

eg.
var optionListener = function() { ... }
document.getElementById('option_comments_checkbox').addEventListener('change', optionListener)
document.getElementById('option_collapse_checkbox').addEventListener('change', optionListener)
etc.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 83 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwIwk00jvSZwt_WDyg:-KOwIwk1ZsXpRJcx_TlY:biaamm9) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L83)):_

> ``` JavaScript
>   // when there are categories if adding the first category.
>   if (firstCategory) {
>     this.allowToSetDefaultOptions();
> ```

This might not be called in case of an early return (from the prompt). Is that ok?

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 616 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwJ61bh7qYoe10inrN:-KOwJ61c41UarxUPGU9B:b-kzre66) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L616)):_

> ``` JavaScript
>         controller.setMode(FactoryController.MODE_TOOLBOX);
>         controller.importToolboxFromTree_(tree);
> ```

You can omit line breaks here :)

The last line before the } shouldn't be empty.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 889 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwJw6ZivYjhvj3j0Xj:-KOwJw6ZivYjhvj3j0Xk:b-u1t7y8) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L889)):_

> ``` JavaScript
>   var options = document.getElementById('workspace_options').children;
> 
>   for (var i = 0, option; option = options[i]; i++) {
> ```

While it's cool that this is more automated, it's less readable and harder to debug if things go wrong. The person debugging could potentially need to check several places to spot a problem:
1) html was set up properly
2) how does this method work
3) how does addOption_ work
4) how does generateSubOptionsObj_ work

Instead, you should get and set the options directly from the elements (like the change above). Something like:

options['collapse'] = // get option value from 'options_collapse_checkbox'

This keeps the logic really simple and allows you to remove generateSubOptionsObj_.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 940 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwKXiXYpxR0RWQU0zU:-KOwKXiXYpxR0RWQU0zV:b-lvxqrq) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L940)):_

> ``` JavaScript
>  * @param {!Object} optionsObj Options object to add the attribute to.
>  */
> FactoryController.prototype.addOption_ = function(option, optionsObj) {
> ```

This should be:

getOptionValue_ = function(inputElementName) { ... }

Then from your caller you would just set:

options["collapse"] = getOptionValue("option_collapse_checkbox")

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 370 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwKqWBWM8OsxMKmYCO:-KOwKqWBWM8OsxMKmYCP:ba6xw9b) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_model.js#L370)):_

> ``` JavaScript
>  * @param {Object} value The value of the attribute to add.
>  */
> FactoryModel.prototype.setOptionsAttribute = function(name, value) {
> ```

Can this be removed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41)_

**Comment by edauterman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/index.html, line 772 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwHfmfGxKdzAiOjJ_F:-KP-fxoA0RFVVAGswIPi:br8mc7t) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/index.html#L772)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> I'd prefer this to simpler by adding the change function to each element directly. It's easier just to be explicit instead of relying on naming conditions.
> 
> eg.
> var optionListener = function() { ... }
> document.getElementById('option_comments_checkbox').addEventListener('change', optionListener)
> document.getElementById('option_collapse_checkbox').addEventListener('change', optionListener)
> etc.
> </details>
> Made an optionListener method and explicitly added it as an action listener for each DOM element. Also removed the custom tag (as we talked about).

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 83 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwIwk00jvSZwt_WDyg:-KP-VpwmoKqjmO_1CNgY:b-pta3xk) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L83)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> This might not be called in case of an early return (from the prompt). Is that ok?
> </details>
> Thanks for pointing that out -- that's actually not what I want, so even though the 2 calls to allowToSetDefaultOptions() is more clunky, I put them back in because that's the behavior I want. 

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 616 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwJ61bh7qYoe10inrN:-KP-WIFcHe1JL6_Dlf2A:b65oiwc) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L616)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> You can omit line breaks here :)
> 
> The last line before the } shouldn't be empty.
> </details>
> Got it. Never thought I'd see that comment :D

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 889 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwJw6ZivYjhvj3j0Xj:-KP-gF8cH6uU3i1YzTR4:b-3kzjh4) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L889)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> While it's cool that this is more automated, it's less readable and harder to debug if things go wrong. The person debugging could potentially need to check several places to spot a problem:
> 1) html was set up properly
> 2) how does this method work
> 3) how does addOption_ work
> 4) how does generateSubOptionsObj_ work
> 
> Instead, you should get and set the options directly from the elements (like the change above). Something like:
> 
> options['collapse'] = // get option value from 'options_collapse_checkbox'
> 
> This keeps the logic really simple and allows you to remove generateSubOptionsObj_.
> </details>
> Explicitly set each option for the options object and for the grid and zoom objects.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 940 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwKXiXYpxR0RWQU0zU:-KP-gMhHO6c7z7Es9Z7E:b7v6g3j) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L940)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> This should be:
> 
> getOptionValue_ = function(inputElementName) { ... }
> 
> Then from your caller you would just set:
> 
> options["collapse"] = getOptionValue("option_collapse_checkbox")
> </details>
> Done. Also added an argument for type of input field to eliminate the need for the custom tag that doesn't affect how the options are displayed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 370 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KOwKqWBWM8OsxMKmYCO:-KP-XdYmYAJaqCJxml7z:b3tz4q2) ([raw file](https://github.com/evd2014/blockly/blob/9797ce7b94810c267e4ba88587dc59b61de6f865/demos/blocklyfactory/workspacefactory/wfactory_model.js#L370)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Can this be removed?
> </details>
> Still need it to set the toolbox attribute, which needs to be set in reinjectPreview but shouldn't normally be stored in the options object. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 954 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KP-lIjK41nRLb3t24l6:-KP-lIjK41nRLb3t24l7:b-1i19x3) ([raw file](https://github.com/evd2014/blockly/blob/052795339c6773f53aaad187708bedcd79e71e34/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L954)):_

> ``` JavaScript
>  *    'number', or 'text').
>  */
> FactoryController.prototype.getOptionValue_ = function(optionId, type) {
> ```

Sorry, this would be better as 3 separate methods. It'll make the generateNewOptions method cleaner.

getCheckboxValue_
getTextValue_
getNumberValue_

These could be defined in your util class. It might also be nice to check if closure has helper methods for this.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41)_

**Comment by edauterman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_controller.js, line 954 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/41#-KP-lIjK41nRLb3t24l6:-KP09wKOwzVnj7FjR3S-:bryh4vz) ([raw file](https://github.com/evd2014/blockly/blob/052795339c6773f53aaad187708bedcd79e71e34/demos/blocklyfactory/workspacefactory/wfactory_controller.js#L954)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Sorry, this would be better as 3 separate methods. It'll make the generateNewOptions method cleaner.
> 
> getCheckboxValue_
> getTextValue_
> getNumberValue_
> 
> These could be defined in your util class. It might also be nice to check if closure has helper methods for this.
> </details>
> We talked about not using these methods since there isn't a util class yet and instead just getting the checked or value attribute and parsing the integer if necessary right then. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/41#-:-KP0HwMxqZLjRP025Dy1:bnfp4nl)_

**Pull request closed without merging**
