### PR TITLE
Workspace Factory #9: Import Toolbox XML

### PR DESCRIPTION
**Pull request by edauterman**
Allows user to choose a local file containing toolbox XML and load it into the workspace factory editing space to continue editing it. If the user does not choose a valid XML file, it prints an error message. 

Also adds a "Clear" button to entirely clear the workspace factory editing space. This was trivial to add because it is necessary to clear before loading a toolbox from a file. 
import button

---

This change is [Reviewable](https://reviewable.io/reviews/evd2014/blockly/29)

### CODE REVIEW

**Comment by edauterman** [comment]
+@picklesrus +@vicng +@quachtina96 +@rachel-fenichel 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29#-:-KO7cGQ9oQKVkpFh1DpG:-1297790682)_

**Comment by quachtina96** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 521 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eiPIG7PPMaxRfeT3:-KO7eiPIG7PPMaxRfeT4:1554720499) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L521)):_

> ``` JavaScript
>       if (item.tagName == 'category') {
>         this.createCategory(item.getAttribute('name'), false);
>         this.switchElement(this.model.getElementByIndex(i).id);
> ```

maybe you could provide an alias for
"this.model.getElementByIndex(i)"  at the start of the for loop--might make the code more readable

---

_[demos/workspacefactory/factory_view.js, line 67 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eIeQhSEENfPGwmcK:-KO7eIeQhSEENfPGwmcL:-1158588620) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L67)):_

> ``` JavaScript
> };
> 
> FactoryView.prototype.addEmptyCategoryMessage = function() {
> ```

comment this function

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 476 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eL8euu80wPU7AQkr:-KO7eL8euu80wPU7AQks:1732508873) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L476)):_

> ``` JavaScript
>  * Should contain valid toolbox XML.
>  */
> FactoryController.prototype.import = function(file) {
> ```

Rename to importFile

---

_[demos/workspacefactory/factory_controller.js, line 504 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eU6mu1sn7VVeLm5G:-KO7eU6nOyZvOng6pmIo:37312936) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L504)):_

> ``` JavaScript
>  * @param {!Element} tree XML tree to be loaded to toolbox editing area.
>  */
> FactoryController.prototype.importFromTree = function(tree) {
> ```

Mark as private.

Also, I think parts of this method could be broken up into the Model class. This method would then just update the View after the Model has been updated.

---

_[demos/workspacefactory/factory_controller.js, line 508 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eXAFlazug1zAfy3q:-KO7eXAFlazug1zAfy3r:598538880) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L508)):_

> ``` JavaScript
>   this.model.clearToolboxList();
>   this.view.clearToolboxTabs();
>   // No categories present.
> ```

Move the "No categories present" inside the if block.

Add line break above this line. It's hard to read a method if it's written without line breaks separating "paragraphs" of code.

---

_[demos/workspacefactory/factory_controller.js, line 515 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7if6BzJPmRXTJ8-UJ:-KO7if6CSmk5m_cX_36H:1522568366) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L515)):_

> ``` JavaScript
>     // Add message to denote empty category.
>     this.view.addEmptyCategoryMessage();
>   // Categories/separators present.
> ```

Move this comment inside the else block.

---

_[demos/workspacefactory/factory_controller.js, line 518 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7j3Q4UrKkLiNTj-J2:-KO7j3Q4UrKkLiNTj-J3:-606686457) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L518)):_

> ``` JavaScript
>   } else {
>     for (var i = 0, item; item = tree.children[i]; i++) {
>       // If the element is a category, create a new category and switch to it
> ```

Move this inside the if statement

---

_[demos/workspacefactory/factory_controller.js, line 523 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jvGxRchYuHE4xJra:-KO7jvGxRchYuHE4xJrb:1946257668) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L523)):_

> ``` JavaScript
>         this.switchElement(this.model.getElementByIndex(i).id);
>         var category = this.model.getElementByIndex(i);
>         // Add all blocks to the category.
> ```

Add line break above this line.

---

_[demos/workspacefactory/factory_controller.js, line 525 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jgnBk7_1tFEAHi9x:-KO7jgnBk7_1tFEAHi9y:-324500272) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L525)):_

> ``` JavaScript
>         // Add all blocks to the category.
>         for (var j = 0, blockXml; blockXml = item.children[j]; j++) {
>           var block = Blockly.Xml.domToBlock(blockXml, this.toolboxWorkspace);
> ```

Is block supposed to be assigned to the category?

---

_[demos/workspacefactory/factory_controller.js, line 527 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jy5xINFqARxmtjrp:-KO7jy5xINFqARxmtjrq:1946257668) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L527)):_

> ``` JavaScript
>           var block = Blockly.Xml.domToBlock(blockXml, this.toolboxWorkspace);
>         }
>         // Evenly space the blocks.
> ```

Add line break above this line.

---

_[demos/workspacefactory/factory_controller.js, line 533 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7j0jN_KMqXcWGQ--m:-KO7j0jN_KMqXcWGQ--n:2124655233) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L533)):_

> ``` JavaScript
>           category.changeColor(item.color);
>         }
>       // If the element is a separator, add the separator and switch to it.
> ```

Move this inside the else block

---

_[demos/workspacefactory/factory_controller.js, line 540 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7k5tBNfIuTrJ2EOBH:-KO7k5tBNfIuTrJ2EOBI:1946257668) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L540)):_

> ``` JavaScript
>     }
>   }
>   this.updatePreview();
> ```

Add line break above this line.

---

_[demos/workspacefactory/factory_view.js, line 62 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7kOd6uoqfm4ufyUP_:-KO7kOd6uoqfm4ufyUPa:1946257668) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L62)):_

> ``` JavaScript
>   var count = table.rows.length;
>   table.deleteRow(index);
>   // If last category removed, add category help text and disable category
> ```

Add line break above this line.

---

_[demos/workspacefactory/factory_view.js, line 267 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7kr4y3WsF7RwG7AAb:-KO7kr4y3WsF7RwG7AAc:1306379792) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L267)):_

> ``` JavaScript
>  * be moved. Must be rendered.
>  */
> FactoryView.prototype.distributeBlocks = function(blocks) {
> ```

Can it be changed so the blocks are spaced relative to each other (not by absolute value relative to the workspace)? This can be a TODO. Might want to check with someone else to see if there's a method that exists in the library for this already too.

---

_[demos/workspacefactory/index.html, line 36 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7lMoupjBopQdJqyCc:-KO7lMoupjBopQdJqyCd:928505563) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/index.html#L36)):_

> ``` HTML
>         <button id="button_print">Print</button>
>         <input type="file" id="input_import" class="inputfile"></input>
>         <label for="input_import">Import</label>
> ```

Move Import before Export?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Comment by edauterman** [comment]
Review status: 0 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

_[demos/workspacefactory/factory_controller.js, line 476 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eL8euu80wPU7AQkr:-KOCTmYoiF2EcG_ETqo_:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L476)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Rename to importFile
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 504 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eU6mu1sn7VVeLm5G:-KOCTsEcJpE_yg68mFYl:-999423773) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L504)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Mark as private.
> 
> Also, I think parts of this method could be broken up into the Model class. This method would then just update the View after the Model has been updated.
> </details>
> Marked as private, and we talked about leaving all of this in the controller.

---

_[demos/workspacefactory/factory_controller.js, line 508 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eXAFlazug1zAfy3q:-KOCWIWTqaiyZfaWsz4p:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L508)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Move the "No categories present" inside the if block.
> 
> Add line break above this line. It's hard to read a method if it's written without line breaks separating "paragraphs" of code.
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 515 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7if6BzJPmRXTJ8-UJ:-KOCUCpiEe2n8bIjIDY7:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L515)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Move this comment inside the else block.
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 518 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7j3Q4UrKkLiNTj-J2:-KOCUDKEsHP14Dcc9PAO:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L518)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Move this inside the if statement
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 521 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eiPIG7PPMaxRfeT3:-KOCVn8U9g4eWPl6Xgzr:1288106199) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L521)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> maybe you could provide an alias for
> "this.model.getElementByIndex(i)"  at the start of the for loop--might make the code more readable
> </details>
> Done by reordering.

---

_[demos/workspacefactory/factory_controller.js, line 523 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jvGxRchYuHE4xJra:-KOCVsuM_BAVlOFfCdqv:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L523)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Add line break above this line.
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 525 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jgnBk7_1tFEAHi9x:-KOCVtyEW9oMS_xjNmKF:-1522997150) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L525)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Is block supposed to be assigned to the category?
> </details>
> It's being loaded into the workspace, properly spaced, and then saved. Clarified comment.

---

_[demos/workspacefactory/factory_controller.js, line 527 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jy5xINFqARxmtjrp:-KOCUOTsRTsGkfCkcX2S:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L527)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Add line break above this line.
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 533 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7j0jN_KMqXcWGQ--m:-KOCUOF5J_ola62_KxYm:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L533)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Move this inside the else block
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 540 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7k5tBNfIuTrJ2EOBH:-KOCUREDOhfe1EOHFjKE:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L540)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Add line break above this line.
> </details>
> Done.

---

_[demos/workspacefactory/factory_view.js, line 62 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7kOd6uoqfm4ufyUP_:-KOCUhgNTbyIY08u17D4:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L62)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Add line break above this line.
> </details>
> Done.

---

_[demos/workspacefactory/factory_view.js, line 67 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7eIeQhSEENfPGwmcK:-KOCUi9GqapB7uDDko6w:2104334560) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L67)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> comment this function
> </details>
> Oops thanks!

---

_[demos/workspacefactory/factory_view.js, line 267 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7kr4y3WsF7RwG7AAb:-KOCV2e448aQThl9GYHU:-1104666982) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L267)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Can it be changed so the blocks are spaced relative to each other (not by absolute value relative to the workspace)? This can be a TODO. Might want to check with someone else to see if there's a method that exists in the library for this already too.
> </details>
> Added as a TODO for now, will check to see if this exists. 

---

_[demos/workspacefactory/index.html, line 36 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7lMoupjBopQdJqyCc:-KOCVHc-bh9lwqSZL8IQ:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/index.html#L36)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Move Import before Export?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Comment by edauterman** [comment]
Review status: 0 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

_[demos/workspacefactory/factory_view.js, line 267 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7kr4y3WsF7RwG7AAb:-KOCnPM29N8pcJRanK50:-422447618) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_view.js#L267)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> Added as a TODO for now, will check to see if this exists. 
> </details>
> Just found WorkspaceSvg.cleanUp_() which does exactly that, so removed distributeBlocks() and replaced it with that. Submitted a pull request to Blockly develop for making cleanUp_() public, and once that gets changed on master, I'll change the call to clean up the blocks to be cleanUp() (added TODO). 

I'm also planning on taking out XY attributes in standardCategories and using cleanUp_() for layout there as well (future CL). 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Comment by vicng** [comment]
Review status: 0 of 7 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

_[demos/workspacefactory/factory_controller.js, line 525 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jgnBk7_1tFEAHi9x:-KOD9WBQvoetYgpzX_mQ:-760943673) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L525)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> It's being loaded into the workspace, properly spaced, and then saved. Clarified comment.
> </details>
> Remove `var block =`?

---

_[demos/workspacefactory/factory_controller.js, line 502 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KODA41V7h5xYNo3fngX:-KODA41V7h5xYNo3fngY:1119236765) ([raw file](https://github.com/evd2014/blockly/blob/7b5435c69d1e7b32cd30cba6ac8525ef2fefaf40/demos/workspacefactory/factory_controller.js#L502)):_

> ``` JavaScript
>  * XML format.
>  *
>  * @package
> ```

`@private`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Comment by edauterman** [comment]
Review status: 0 of 7 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

_[demos/workspacefactory/factory_controller.js, line 525 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KO7jgnBk7_1tFEAHi9x:-KOGIJJEu-cbhgwxTywQ:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/0d52c2dec7863009e004682b628649a7674a9d9f/demos/workspacefactory/factory_controller.js#L525)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Remove `var block =`?
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 502 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KODA41V7h5xYNo3fngX:-KOGI-mLO6KmZo89Klz9:-399451063) ([raw file](https://github.com/evd2014/blockly/blob/7b5435c69d1e7b32cd30cba6ac8525ef2fefaf40/demos/workspacefactory/factory_controller.js#L502)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> `@private`?
> </details>
> I'll change that. Saw @package in the Closure documentation and thought I was supposed to use that, but I'll use @private.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Comment by picklesrus** [comment]
:lgtm: When vicng is happy.

---

Review status: 0 of 6 files reviewed at latest revision, 16 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 502 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KODA41V7h5xYNo3fngX:-KOHdbF803WnoIq8TecO:-1650317324) ([raw file](https://github.com/evd2014/blockly/blob/7b5435c69d1e7b32cd30cba6ac8525ef2fefaf40/demos/workspacefactory/factory_controller.js#L502)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> I'll change that. Saw @package in the Closure documentation and thought I was supposed to use that, but I'll use @private.
> </details>
> if its only called from this class then yeah, you want private.  package is used in blocky in places where we want to be able use stuff inside of blockly, but not have it visible to developers (e.g. the workspace tells the flyout to do something that we don't ) 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29#-:-KOHgLXfQFoVfs9k8W-P:700027030)_

**Comment by vicng** [comment]
:lgtm: after small formatting

---

Review status: 0 of 6 files reviewed at latest revision, 21 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 499 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHh3_otw1GDjT-XHoy:-KOHh3_otw1GDjT-XHoz:1459702804) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L499)):_

> ``` JavaScript
>     return;
>   }
>   var reader = new FileReader();
> ```

Nit: Add line above this

---

_[demos/workspacefactory/factory_controller.js, line 511 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHh50Y_neXaGcihZVh:-KOHh50Y_neXaGcihZVi:1459702804) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L511)):_

> ``` JavaScript
>     }
>   }
>   // Read the file.
> ```

Nit: Add line above this

---

_[demos/workspacefactory/factory_controller.js, line 539 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHgYt7iK3oCSPKQNmI:-KOHgYt7iK3oCSPKQNmJ:1243584623) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L539)):_

> ``` JavaScript
>     for (var i = 0, item; item = tree.children[i]; i++) {
>       if (item.tagName == 'category') {
>       // If the element is a category, create a new category and switch to it.
> ```

Nit: Indentation

---

_[demos/workspacefactory/factory_controller.js, line 559 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHg_VvryZiDvSeU18Z:-KOHg_VvryZiDvSeU18_:1243584623) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L559)):_

> ``` JavaScript
>         }
>       } else {
>       // If the element is a separator, add the separator and switch to it.
> ```

Nit: Indentation

---

_[demos/workspacefactory/factory_model.js, line 255 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHhHr_CgAO_T4S3Fpd:-KOHhHr_CgAO_T4S3Fpe:689584825) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_model.js#L255)):_

> ``` JavaScript
> FactoryModel.prototype.clearToolboxList = function() {
>   this.toolboxList = [];
>   // TODO: When merge changes, also clear shadowList.
> ```

Nit: Add your name to the TODO

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29#-:-KOHhMYRqQUoH_sdrc6Y:511069201)_

**Comment by edauterman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 21 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 499 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHh3_otw1GDjT-XHoy:-KOHixVqbqrCMvya0LnS:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L499)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Add line above this
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 511 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHh50Y_neXaGcihZVh:-KOHiy8SteEKbwGqER6L:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L511)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Add line above this
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 539 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHgYt7iK3oCSPKQNmI:-KOHj5cZAZM35XoV9PIE:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L539)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Indentation
> </details>
> Done.

---

_[demos/workspacefactory/factory_controller.js, line 559 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHg_VvryZiDvSeU18Z:-KOHj8sOc9fhetn-1bdR:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_controller.js#L559)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Indentation
> </details>
> Done.

---

_[demos/workspacefactory/factory_model.js, line 255 [r6]](https://reviewable.io:443/reviews/evd2014/blockly/29#-KOHhHr_CgAO_T4S3Fpd:-KOHjMhT_-y-CpqrbSwT:-499146009) ([raw file](https://github.com/evd2014/blockly/blob/f20a519a702e85cc8ef93b07c861bc051574b9cf/demos/workspacefactory/factory_model.js#L255)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Add your name to the TODO
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/29)_

**Pull request merged**
