### PR TITLE
Workspace Factory #17: Get block types currently used

### PR DESCRIPTION
**Pull request by edauterman**
Added function in generator that returns an array of all the block types being used without any duplicates. For use in integrating with Blockly Factory to allow the exporter to know which blocks are being used in the toolbox and pre-loaded blocks. This will allow the exporter to be able to automatically add all blocks currently being used in workspace factory to the selector workspace.

---

This change is [Reviewable](https://reviewable.io/reviews/evd2014/blockly/42)

### CODE REVIEW

**Comment by edauterman** [comment]
+@picklesrus +@vicng +@quachtina96 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42#-:-KOvUg4q6c1pwrlzNhKH:b-wq1gnr)_

**Comment by vicng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 119 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvw2L_d8ZTxZI_B_2Q:-KOvw2L_d8ZTxZI_B_2R:b-cmah5f) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L119)):_

> ``` JavaScript
> FactoryGenerator.prototype.getAllUsedBlocks = function() {
>   var blockTypeList = [];
>   if (!this.model.hasElements()) {
> ```

These calls would read nicer as ".isFlyout()", instead of deducing that it's a flyout.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 122 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvwP35O_KIfsBekf6f:-KOvwP35O_KIfsBekf6g:b-nkteu0) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L122)):_

> ``` JavaScript
>     // If has a single flyout, add block types for the single flyout.
>     this.pushBlockTypesToList_(this.model.getSelectedXml(), blockTypeList);
> ```

Nit: Remove extra line.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 127 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvwZ3rY2npXp6hi_WJ:-KOvwZ3rY2npXp6hi_WK:bcu91uq) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L127)):_

> ``` JavaScript
>     var toolboxList = this.model.getToolboxList();
> 
>     for (var i = 0, category; category = this.toolboxList[i]; i++) {
> ```

Remove "this."?

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 153 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvx8LDxM9dg5bafGxH:-KOvx8LDxM9dg5bafGxI:b6h5eiz) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L153)):_

> ``` JavaScript
>   this.hiddenWorkspace.clear();
>   Blockly.Xml.domToWorkspace(xml, this.hiddenWorkspace);
>   var blocks = this.hiddenWorkspace.getAllBlocks();
> ```

Is there a way to get the block type without using the generator's hidden workspace? These two methods seem more appropriate in the Model class, since nothing is being generated here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by quachtina96** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 117 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOwvGpQFCYEOjCHFEIZ:-KOwvGpQFCYEOjCHFEI_:bugbjt7) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L117)):_

> ``` JavaScript
>  * @return {!Array<!string>} Array of block types currently being used.
>  */
> FactoryGenerator.prototype.getAllUsedBlocks = function() {
> ```

'getAllUsedBlockTypes' is more accurate of a name

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 153 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvx8LDxM9dg5bafGxH:-KOwrm0x8PvHQ6le27V9:brm1hck) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L153)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Is there a way to get the block type without using the generator's hidden workspace? These two methods seem more appropriate in the Model class, since nothing is being generated here.
> </details>
> @evd2014  If you are looking to extract the blocktype from the xml,  I have a function AppController.prototype.getBlockTypeFromXml_, which extracts block type from xml text, the kind that is saved in block library storage. I dont think my function does exactly what you want here, but it is not hard to adjust.  Notes here: https://docs.google.com/document/d/1r4ZEBzDFAjCItUHpwfr47-LmFOiIsyPU5CkdA1iSXr8/edit

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by edauterman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 117 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOwvGpQFCYEOjCHFEIZ:-KOzxYTWqnVHgzTdNQCU:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L117)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> 'getAllUsedBlockTypes' is more accurate of a name
> </details>
> Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 119 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvw2L_d8ZTxZI_B_2Q:-KP-U9HubrKGi-rX0pKL:b-8ucm5t) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L119)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> These calls would read nicer as ".isFlyout()", instead of deducing that it's a flyout.
> </details>
> When moved to model, could directly access the flyout ivar. 

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 122 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvwP35O_KIfsBekf6f:-KOzxXzGyRWm0m0G0CgX:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L122)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Remove extra line.
> </details>
> Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 127 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvwZ3rY2npXp6hi_WJ:-KOzxbjkMIrPuMUUY337:bvbzwvn) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L127)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Remove "this."?
> </details>
> Changed to just use this.toolboxList directly now that I'm in the model.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 153 [r1]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KOvx8LDxM9dg5bafGxH:-KP-UL6kH_5ybN9Z1-5O:b-wkyst9) ([raw file](https://github.com/evd2014/blockly/blob/c6d8e0c4ebc2a9cc80ecf468d33a88a378773fd5/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L153)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> @evd2014  If you are looking to extract the blocktype from the xml,  I have a function AppController.prototype.getBlockTypeFromXml_, which extracts block type from xml text, the kind that is saved in block library storage. I dont think my function does exactly what you want here, but it is not hard to adjust.  Notes here: https://docs.google.com/document/d/1r4ZEBzDFAjCItUHpwfr47-LmFOiIsyPU5CkdA1iSXr8/edit
> </details>
> Thanks! Looked through this and came up with something similar to parse the XML for the block type. Refactored to extract block type from the XML and put these functions in the model.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by quachtina96** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 402 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPENXxAVEGf5duSwhMI:-KPENXxAVEGf5duSwhMJ:b-5m3zmx) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L402)):_

> ``` JavaScript
>   for (var i = 0; i < blocks.length; i++) {
>     var type = blocks[i].getAttribute('type');
>     if (list.indexOf(type) == -1) {
> ```

Would it be more efficient to use a set to store the types of blocks and then convert that to an array at the end?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by quachtina96** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42#-:-KPEOeh7k7dHQRQ9x72_:bnfp4nl)_

**Comment by vicng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 363 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFGg6rruV5trPd2Txi:-KPFGg6slv2R0DeFlsbs:b6z2uwn) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L363)):_

> ``` JavaScript
> FactoryModel.prototype.getAllUsedBlockTypes = function() {
>   var blockTypeList = [];
>   console.log(this.getSelectedXml());
> ```

Remove this log and just add an empty line.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 366 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFGin21uprhvhbGdy1:-KPFGin21uprhvhbGdy2:b4uajcw) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L366)):_

> ``` JavaScript
>   if (this.flyout) {
>     // If has a single flyout, add block types for the single flyout.
> ```

You can remove this extra line

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 395 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFH8i4aerf8zg4dWXd:-KPFH8i4aerf8zg4dWXe:bfwa46u) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L395)):_

> ``` JavaScript
>  * @param {!Array<!string>} list The array of block types to add to.
>  */
> FactoryModel.prototype.pushBlockTypesToList_ = function (xml, list) {
> ```

Unless this will be used elsewhere, can this be defined as an inline function inside getAllUsedBlockTypes?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by edauterman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 363 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFGg6rruV5trPd2Txi:-KPFKlathWhlS-TUVSLA:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L363)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Remove this log and just add an empty line.
> </details>
> Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 366 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFGin21uprhvhbGdy1:-KPFKodlsfpl4VXankZ5:b-896fix) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L366)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> You can remove this extra line
> </details>
> Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 395 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFH8i4aerf8zg4dWXd:-KPFNxw1tFTFqcvGPG1x:b-cm8trr) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L395)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Unless this will be used elsewhere, can this be defined as an inline function inside getAllUsedBlockTypes?
> </details>
> Actually was just planning some stuff with Tina and this function will be used elsewhere. Removed the @private tag. 

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 402 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPENXxAVEGf5duSwhMI:-KPFO3efraoktjLwgpwz:b-naiq0z) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L402)):_
<details><summary>

<i>Previously, quachtina96 (Tina Quach) wrote…</i></summary>



> Would it be more efficient to use a set to store the types of blocks and then convert that to an array at the end?
> </details>
> We talked about this offline, and IE support for Sets is pretty minimal.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by vicng** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 120 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPG10mN7Z7-Ye9sCT1V:-KPG10mN7Z7-Ye9sCT1W:b-7i0ia3) ([raw file](https://github.com/evd2014/blockly/blob/787e3daea3bd22f7ad322d36d2928ea345ac622a/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L120)):_

> ``` JavaScript
>  * @param {!Element} dom The DOM element to append the generated XML to.
>  */
> FactoryGenerator.prototype.loadToHiddenWorkspaceAndSave_ = function(xml, dom) {
> ```

There should only be one method that controls loading data into the hidden workspace.

This method should just be `loadToHiddenWorkspace_` and it shouldn't call `appendHiddenWorkspaceToDom_`. Once that's fixed, then you can call it in `generateWorkspaceXml`.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 395 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFH8i4aerf8zg4dWXd:-KPG0JIP0PmSiHKiSZrG:byy7ywm) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L395)):_
<details><summary>

<i>Previously, evd2014 (Emma Dauterman) wrote…</i></summary>



> Actually was just planning some stuff with Tina and this function will be used elsewhere. Removed the @private tag. 
> </details>
> This doesn't belong as a Model method. It isn't using anything Model specific.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by edauterman** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[demos/blocklyfactory/workspacefactory/wfactory_generator.js, line 120 [r3]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPG10mN7Z7-Ye9sCT1V:-KPJE_-YzJEDcoHL9MbP:bh7t6wr) ([raw file](https://github.com/evd2014/blockly/blob/787e3daea3bd22f7ad322d36d2928ea345ac622a/demos/blocklyfactory/workspacefactory/wfactory_generator.js#L120)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> There should only be one method that controls loading data into the hidden workspace.
> 
> This method should just be `loadToHiddenWorkspace_` and it shouldn't call `appendHiddenWorkspaceToDom_`. Once that's fixed, then you can call it in `generateWorkspaceXml`.
> </details>
> That makes sense. Done.

---

_[demos/blocklyfactory/workspacefactory/wfactory_model.js, line 395 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/42#-KPFH8i4aerf8zg4dWXd:-KPJDlN7L6d6GdE6XcHr:beu67ot) ([raw file](https://github.com/evd2014/blockly/blob/8511373020b29443222428b00254ead409d3b0a2/demos/blocklyfactory/workspacefactory/wfactory_model.js#L395)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> This doesn't belong as a Model method. It isn't using anything Model specific.
> </details>
> Completely agreed. The reason I left it in the model even though I didn't think it was the best place for it was because getAllUsedBlockTypes needed access to it, and the model doesn't have access to any methods outside the model. I added a TODO to move it to FactoryUtils once this CL gets merged into the develop branch. For now, I made it an inline function inside getAllUsedBlockTypes like you initially recommended.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/42#-:-KPKN3MQq_5Uq_8y9zXk:bnfp4nl)_

**Pull request closed without merging**
