### PR TITLE
Workspace Factory #4: Category Color

### PR DESCRIPTION
**Pull request by edauterman**
The user can now pick a color for their category given a choice of colors. The user chooses colors through the Closure PopupColorPicker, which is initialized with Blockly specific colors, and their choice of colors shows up as a left border on the category tab in the view (to look similar to the Blockly toolbox UI). 

Also made the few small changes suggested by picklesrus and vicng in the last CL. 
color screenshot

---

This change is [Reviewable](https://reviewable.io/reviews/evd2014/blockly/24)

### CODE REVIEW

**Comment by edauterman** [comment]
+@picklesrus +@vicng +@quachtina96 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/24#-:-KNZFsG6hKUEDmgMy5bn:-1978655895)_

**Comment by picklesrus** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[demos/workspacefactory/index.html, line 510 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/24#-KNZOa61boChV5j5ykPq:-KNZOZfz1xAON0w91ghn:-784876296) ([raw file](https://github.com/evd2014/blockly/blob/07a02bc3b8ff51226539ee83ef0038519cf349ec/demos/workspacefactory/index.html#L510)):_

> ``` HTML
>   goog.events.listen(popupPicker, 'change', function(e) {
>         controller.changeColor(popupPicker.getSelectedColor());
>       });
> ```

I think indentation is off here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/24#-:-KNZQ_atCvpvqN87W1oc:1417088721)_

**Comment by vicng** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 344 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/24#-KNZSfN2L8sr5LjeZZeR:-KNZSfN2L8sr5LjeZZeS:-924835717) ([raw file](https://github.com/evd2014/blockly/blob/07a02bc3b8ff51226539ee83ef0038519cf349ec/demos/workspacefactory/factory_controller.js#L344)):_

> ``` JavaScript
>  * a valid CSS string.
>  */
> FactoryController.prototype.changeColor = function(color) {
> ```

Nit: Rename changeSelectedCategoryColor

I think changeColor is a bit too vague since this controller is basically the only entry point that the app is talking to.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/24#-:-KNZUSvoQNupr5cF4bzN:1417088721)_

**Comment by edauterman** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_[demos/workspacefactory/factory_controller.js, line 344 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/24#-KNZSfN2L8sr5LjeZZeR:-KNZbUC0bUTUYVzW77w_:-609445857) ([raw file](https://github.com/evd2014/blockly/blob/07a02bc3b8ff51226539ee83ef0038519cf349ec/demos/workspacefactory/factory_controller.js#L344)):_
<details><summary>

<i>Previously, vicng wrote…</i></summary>



> Nit: Rename changeSelectedCategoryColor
> 
> I think changeColor is a bit too vague since this controller is basically the only entry point that the app is talking to.
> </details>
> Changed.

---

_[demos/workspacefactory/index.html, line 510 [r2]](https://reviewable.io:443/reviews/evd2014/blockly/24#-KNZOa61boChV5j5ykPq:-KNZbWuuFkrMCN8W-c1q:1910608427) ([raw file](https://github.com/evd2014/blockly/blob/07a02bc3b8ff51226539ee83ef0038519cf349ec/demos/workspacefactory/index.html#L510)):_
<details><summary>

<i>Previously, picklesrus wrote…</i></summary>



> I think indentation is off here.
> </details>
> We talked about this and no changes necessary.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/evd2014/blockly/24)_

**Pull request merged**
